from argparse import ArgumentParser
from pathlib import Path

from crafter import run_crafter as execute_crafter


def parse_args():
    parser = ArgumentParser(description="Run the novum pipeline by orchestrating crafter.py and arranger.R.")

    # crafter.py arguments
    parser.add_argument("-q", "--query", required=True, help="Query FASTA file.")
    parser.add_argument("-t", "--target", required=True, help="Target FASTA file.")
    parser.add_argument("-s", required=True, help="RNAhybrid species model (3utr_fly|3utr_worm|3utr_human).")
    parser.add_argument("-b", "--hits", type=int, help="Number of hits per target.")
    parser.add_argument("-u", type=int, help="Max internal loop size (per side).")
    parser.add_argument("-v", type=int, help="Max bulge loop size.")
    parser.add_argument("-e", "--energy", type=int, help="Energy cut-off.")
    parser.add_argument("-p", "--pvalue", type=float, help="P-value cut-off.")
    parser.add_argument("-f", "--seed", help="Helix constraint: 'from,to'.")

    # Pipeline outputs
    parser.add_argument("--intermediate-output", default="data/results/output.tsv", help="Path for the RNAhybrid output generated by crafter.py.")
    parser.add_argument("--final-output", help="Reserved for the future arranger.R output path.")

    # Future arranger.R parameters
    parser.add_argument("--arranger-script", default="arranger.R", help="Path to arranger.R. Parsed now for future orchestration.")
    parser.add_argument("--dry-run-arranger", action="store_true", help="Print the future arranger.R command instead of running it.")

    return parser.parse_args()


def build_arranger_command(args):
    # Placeholder only: the final CLI for arranger.R still needs to be defined.
    command = [
        "Rscript",
        args.arranger_script,
        args.intermediate_output,
    ]

    if args.final_output is not None:
        command.append(args.final_output)

    return command


def run_crafter_stage(args):
    intermediate_output = Path(args.intermediate_output)
    intermediate_output.parent.mkdir(parents=True, exist_ok=True)

    execute_crafter(
        query=args.query,
        target=args.target,
        species=args.s,
        output_file=args.intermediate_output,
        hits=args.hits,
        u=args.u,
        v=args.v,
        energy=args.energy,
        pvalue=args.pvalue,
        seed=args.seed
    )

    if not intermediate_output.exists():
        raise RuntimeError(f"crafter.py completed but did not produce the expected file: {intermediate_output}")


def main():
    args = parse_args()
    run_crafter_stage(args)

    # arranger.R is intentionally not executed yet.
    # Its final interface still needs to be designed, so main.py only prepares the handoff.
    if args.dry_run_arranger:
        print("Future arranger.R command draft:")
        print(" ".join(build_arranger_command(args)))


if __name__ == "__main__":
    main()